# Generated by Django 5.0 on 2024-07-25 11:43

import ferramentas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='created_at',
            field=models.DateTimeField(default=ferramentas.models.default_created_at),
        ),
    ]
