# Generated by Django 5.0 on 2024-07-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0002_formulario_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
