# Generated by Django 5.0 on 2024-07-25 12:01

import ferramentas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0003_alter_formulario_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='created_at',
            field=models.DateTimeField(default=ferramentas.models.default_created_at),
        ),
    ]
